version: '3.8'
networks:
  rapture:

services:
  apache:
    image: httpd:2.4
    ports:
      - 8080:80
    volumes:
      - ./server/apache/my-httpd.conf:/usr/local/apache2/conf/httpd.conf
      - ./server/apache/vhost.conf:/usr/local/apache2/conf/extra/httpd-vhosts.conf
      - ./app:/usr/local/apache2/htdocs
    depends_on:
      - php
    networks:
      - rapture

  php:
    build:
      context: ./server/php/
      args:
        USER_ID: ${USER_ID}
        GROUP_ID: ${GROUP_ID}
    volumes:
      - ./app:/var/www/html/
      - ./server/php/php.ini-development:/usr/local/etc/php/php.ini
      - ./server/php/php.ini:/usr/local/etc/php/conf.d/custom.ini
    ports:
      - "9000:9000"
    networks:
      - rapture

  db:
    image: mysql
    hostname: db
    command: --default-authentication-plugin=mysql_native_password --character-set-server=utf8 --collation-server=utf8_general_ci
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: app_db
    volumes:
      - ./server/db_data:/var/lib/mysql
    networks:
      - rapture

  phpmyadmin:
    depends_on:
      - db
    image: phpmyadmin/phpmyadmin
    ports:
      - '8070:80'
    environment:
      PMA_HOST: db
      MYSQL_ROOT_PASSWORD: root
    networks:
      - rapture